### ISSUE TITLE
Documentation on how to contribute

### ISSUE THREAD

**Issue by Blue-Robin-Taken** [Mr-Ben-Merch-Store/Website#24]
What if we make a page called "How To Contribute" which documents how to push, pull, commit, etc. from github?
It'd be super helpful to newcomers.

**Comment by LizzyEll** [comment]
Remove my old git from the project,
I think this would be a very good idea, but to set it up, i would need to make a way for us to comunicate other than github comments. Working on it soon

**Comment by RedCat888** [comment]
I think we could integrate the "How to Contribute" portion in the README.md. It already appears on the front page of the repo and would be visisble to a ton of people

**Comment by LizzyEll** [comment]
> I think we could integrate the "How to Contribute" portion in the README.md. It already appears on the front page of the repo and would be visisble to a ton of people

Big brains, sounds good

**Comment by Blue-Robin-2** [comment]
@Lunarware-xyz I'm going to try to implement that now.
Also, I removed your git from the project quite a while ago

**Comment by LizzyEll** [comment]
Thank you
