### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by LizzyEll** [Mr-Ben-Merch-Store/Website#35]
I think it would be a good consideration to put all the pages except the main index.html into a `/pages/` folder and to put the sidebar template thing into a `/templates/` folder.

**Comment by RedCat888** [comment]
I think having the main ones like index.html, about.html, cart.html, and products/merch.html should just be under /website.), while all the merchandise pages should be in another folder like you said

**Comment by LizzyEll** [comment]
That works perfect.
