### ISSUE TITLE
Color scheme bland

### ISSUE THREAD

**Issue by LizzyEll** [Mr-Ben-Merch-Store/Website#41]
Yeah so the site looks kinda bland, maybe different colors?

heres a couple ideas
[Theme #1](https://www.realtimecolors.com/?colors=dafcff-03272b-4e0c7e-011719-77e9f4&fonts=Poppins-Poppins)
and
[Theme #2](https://www.realtimecolors.com/?colors=f8e7f4-280620-8f0070-3e0432-be37a1&fonts=Poppins-Poppins)

**Comment by Blue-Robin-2** [comment]
What about:
https://www.realtimecolors.com/?colors=fcf9f8-180f0c-6aa3b4-221511-5596aa&fonts=Poppins-Poppins

**Comment by LizzyEll** [comment]
I like it but for the background it's a little too red.

**Comment by RedCat888** [comment]
I think the website is fine as it is. It looks bland because we haven't added anything. I kinda like the minimalistic look using the colors I chose

**Comment by LizzyEll** [comment]
you only chose those colors because they are the exact same color and design of your main portfolio page

**Comment by RedCat888** [comment]
Bruh I forked this site from the portfolio lmao. Look at dates before saying anything. I chose the colors because they looked nice and clean

**Comment by LizzyEll** [comment]
mhm mhm, "clean"

**Comment by RedCat888** [comment]
Do you come to CS forum meetings? Take a vote to see if we should keep it or change it.

**Comment by Lunarware-xyz** [comment]
I don't currently. I attend Lowery Freshman Center and I am currently a part of the LFC Theatre Production Radium Girls so I have rehersal on wednesdays after school.

**Comment by Blue-Robin-2** [comment]
@Lunarware-xyz This is a public repo. Please don't include any PII

**Comment by LizzyEll** [comment]
No, i don't*

**Comment by Blue-Robin-Taken** [comment]
Closed the issue cause we don't really need to work on this right now
