### ISSUE TITLE
Our website is blocked by goguardian

### ISSUE THREAD

**Issue by Blue-Robin-2** [Mr-Ben-Merch-Store/Website#61]
**Describe the bug**
OUR WEBSITE IS BLOCKED!

**To Reproduce**
1. Go to our website on a school Chromebook
2. See error

**Expected behavior**
Our website should work

**Screenshots**
![image](https://github.com/Mr-Ben-Merch-Store/Website/assets/102540302/88bc28f4-6ffa-4007-8dde-852f8016478d)

**Additional context**
How do we unblock it?

**Comment by LizzyEll** [comment]
They blocked all of `vercel.app`, not much we can do but ask Mr. Ben if he can put out a request to the district via helpdesk.allenisd.org.

**Comment by Blue-Robin-2** [comment]
I made a help ticket

**Comment by LizzyEll** [comment]
It has to be from Mr. Ben, they don't accept requests from students for unblocking websites.

**Comment by Blue-Robin-Taken** [comment]
I emailed Mr. Ben

**Comment by Blue-Robin-2** [comment]
still a problem

**Comment by Blue-Robin-2** [comment]
Should I email the other CS teacher?

**Comment by RedCat888** [comment]
Yes, do email the other teacher. It's blocked and that's not acceptable for them to blindly block everything with that domain. In fact, I was considering to email the IT admins

**Comment by RedCat888** [comment]
I emailed someone and here's their reply:

![Uploading Screenshot 2023-12-12 11.54.22 AM.png…]()

**Comment by Lunarware-xyz** [comment]
I don't mean to be that person, but remove personal info?

**Comment by Blue-Robin-Taken** [comment]
What'd they comment?

**Comment by Blue-Robin-Taken** [comment]
Thanks for deleting that.

**Comment by RedCat888** [comment]
![Screenshot 2023-12-12 11 54 22 AM](https://github.com/Mr-Ben-Merch-Store/Website/assets/84790240/38f065df-a78e-4d63-a6df-8b9b4978fd9f)

**Comment by Blue-Robin-Taken** [comment]
our school needs to change...
Did you send an email to the CS-1 teacher?

**Comment by Blue-Robin-Taken** [comment]
Did you send an email to the CS-1 teacher?

**Comment by Blue-Robin-Taken** [comment]
What we could do is:
1. Get a new domain
2. Route to that domain
3. Tell a CS teacher to unblock that domain

**Comment by LizzyEll** [comment]
If you add me on discord @LizzyEll *, we can test the idea with a couple of my domains that are unblocked by the district.

\* Public Information

**Comment by RedCat888** [comment]
You can use namecheap to route one domain to another. I can help out later sometime.

**Comment by LizzyEll** [comment]
That's using a CNAME record which also requires extra configuration that Vercel does not support. Vercel has a separate menu for connecting domains using an A record to their servers' IPs. That's what I was mentioning earlier.
```
A:       Domain -> IP
CNAME:   Domain -> Domain
```

**Comment by RedCat888** [comment]
That's what I meant, to use an "A" record, although I didn't know you could
do that in vercel itself

**Comment by Blue-Robin-Taken** [comment]
What comment did you delete from me? @Lunarware-xyz

**Comment by LizzyEll** [comment]
I deleted the comments about the issue with personal information and edited out unneeded extra information.

**Comment by Blue-Robin-Taken** [comment]
I don't think I had any personal information anywhere

**Comment by LizzyEll** [comment]
not you, I deleted the comments about @RedCat888 's incident.

**Comment by Blue-Robin-Taken** [comment]
![Screenshot 2024-01-17 8 51 36 AM](https://github.com/Mr-Ben-Merch-Store/Website/assets/86581171/dc716b6d-02b6-4e42-8d7c-153434a63157)

**Comment by Blue-Robin-Taken** [comment]
Github bug?

**Comment by LizzyEll** [comment]
I also deleted my comments and a couple of theirs, mine just doesn't show when I delete my own.

**Comment by LizzyEll** [comment]
[Temporary Site Link](https://ben.lunarware.tech/)? I just built it and slapped it on my server lmao. Also, my Domains are unrestricted from the district 😎. I know the main IT person personally. (church)

**Comment by RedCat888** [comment]
That seems like a decent alternative at the moment.

**Comment by Blue-Robin-Taken** [comment]
Sounds good. As long as changes are pushed to the new domain then that's awesome.

**Comment by LizzyEll** [comment]
ummm..... about that...
I'll have to set that up ig? idk haha

**Comment by LizzyEll** [comment]
The website is now available at `https://ben.lunarware.tech`. The issue of a pending dedicated domain has been opened (Issue #69).

**Comment by RedCat888** [comment]
Our new domain, bensmerch.org is blocked by CK-express for being "unmanaged," because we aren't using an website management service, we're hosting it ourselves on vercel. We need to reach out to the IT department.

**Comment by Blue-Robin-Taken** [comment]
I'm closing this because it's a bit dated (goguardian doesn't block it but the school's wifi does, which is problematic)
I'll make a new git issue

**Comment by RedCat888** [comment]
ok
