### ISSUE TITLE
Footer doesn't properly display

### ISSUE THREAD

**Issue by Blue-Robin-Taken** [Mr-Ben-Merch-Store/Website#67]
**Describe the bug**
The footer isn't at the bottom for some pages. This is only for the home page however.

**To Reproduce**
1. Go to [the newest preview of the project](https://mr-bens-merch-store-n3xtr9nkt-julian-thomas-projects.vercel.app/)
2. Go to the home page
3. See the error

**Expected behavior**
It looks like the following (currently):
![image](https://github.com/Mr-Ben-Merch-Store/Website/assets/86581171/dc821089-6ad0-456e-99cd-34676e10a60f)
Here's what it should look like (where the arrows are)
![image](https://github.com/Mr-Ben-Merch-Store/Website/assets/86581171/991e68c7-f5c0-433f-9948-36390ab2d652)

**Comment by RedCat888** [comment]
I think it needs to have the "sticky" tag/class within <div x>

I'll look into it

**Comment by LizzyEll** [comment]
Maybe this?
```css
Element {
    position: absolute;
    bottom: 0;
}
```

**Comment by Blue-Robin-Taken** [comment]
Sure, try it
