### ISSUE TITLE
We need a Domain.

### ISSUE THREAD

**Issue by LizzyEll** [Mr-Ben-Merch-Store/Website#69]
# We need a Domain.

As of right now, we are hosting the Merch Store with Vercel (static html) and we are using one of their sub-domains to achieve this. I am not opposed to using Vercel to host the Merch Store but we should use our own domain both for legitimacy and for simplicity. Vercel has an extremely easy option that I believe would be best for both us and the Merch Store. Vercel has a built in option that makes using a BYOD (bring your own domain) very simple and easy to manage. In other words, on [NameCheap](https://namecheap.com), the Domain `MrBen.store` is on sale for $1 every year and I feel that this is an amazing opportunity to improve our application. I would be willing to pay this fee and transfer the domain to @Blue-Robin-Taken where he could manage it since they have issues trusting me.

EDIT:
Another option is obtaining a sub-domain of the `AHSChillStudy.com` domain.

---
```
Lizzy Ell
Lizzy@lunarware.tech
Allen High School
Cyber Security
```

**Comment by LizzyEll** [comment]
@Blue-Robin-Taken , have anything to say?

**Comment by Blue-Robin-Taken** [comment]
I could buy the name myself, but we'd need an admin or a teacher to unblock the domain that we buy

**Comment by LizzyEll** [comment]
That's true. I could try with my inside knowlodge but I couldn't promise anything.

**Comment by RedCat888** [comment]
Julian purchased a domain on cloudflare at bensmerch.org and pointed it to the vercel URl where the website is hosted. I think it's something like 7 bucks a year and gives us all the great tools that come with cloudflare. Issue closed
